#options
LOGFILE="/var/log/odoo/odoo-autoupdate"
ODOO_PATH="/opt/odoo/14.0"
ODOO_SERVICE="odoo"
ODOO_USER="odoo"
ODOO_CONF="/etc/odoo/odoo.conf"
OCA_FOLDER="/opt/odoo/addons/OCA"
LIMIT=500
CUSTOM_FOLDERS=("/opt/odoo/addons/custom")
FIX_FOLDERS=("/opt/odoo/14.0/addons" "/opt/odoo/14.0/addons/custom")
# set TRUE if you want to skip dependencies installation
SKIP_REQ="true"
# set REQUIREMENTS empty if you want use var+fix folder path to search for requirement, else put desired folder path as "/path1,/path2,/path3"
REQUIREMENTS=
EXCLUDE_REPO='[ "$repo" == "OCA/OCB" ] || [[ "$repo" =~ ^OCA/l10n.* ]] && [ "$repo" != "OCA/l10n-italy" ]'
ODOO_VERS="14.0"
# set VNENV empty if you don't use a virtual environment
VENV="/opt/odoo/venv"
DB_NAME="database14"

#formatted_folders is a variable used by the script
formatted_folders=
